version: "3.8"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "30000:30000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - PORT=30000
    command: npm run dev
